W-11793337 Adding an option to the convert command
salesforcecli/plugin-packaging pull request #123
Opened 2022-10-11 19:01 UTC by smotwani11

@W-11793337@

This PR adds a definition file option to the convert command

2022-10-11 19:17 UTC, peternhale requested changes
@smotwani11 please have a look at the UT for package convert and add tests around definition file.

2022-10-24 17:48 UTC, jshackell-sfdc commented on messages/package_convert.md
> +path to a definition file similar to scratch org definition file that contains the list of features and org preferences that the metadata of the package version depends on
```suggestion
path to a definition file that contains features and org preferences that the metadata of the package version depends on
```

2022-10-24 17:49 UTC, jshackell-sfdc commented on messages/package_convert.md
> +The path to a definition file similar to scratch org definition file that contains the list of features and org preferences that the metadata of the package version depends on.
```suggestion
The path to a definition file, similar to the scratch org definition file, that contains the list of features and org preferences that the metadata of the package version depends on.
```

2022-10-25 17:56 UTC, smotwani11 commented on messages/package_convert.md
> +The path to a definition file similar to scratch org definition file that contains the list of features and org preferences that the metadata of the package version depends on.
I have updated the messages.

2022-10-25 17:56 UTC, smotwani11 commented on messages/package_convert.md
> +path to a definition file similar to scratch org definition file that contains the list of features and org preferences that the metadata of the package version depends on
Thanks. I have updated the messages.

2022-10-25 19:26 UTC, peternhale approved these changes

2022-11-03 18:18 UTC, merged