fix: improve handling of pvc path flag
salesforcecli/plugin-packaging pull request #129
Opened 2022-10-17 12:08 UTC by peternhale

### What does this PR do?
Improves handling of the path flag for package version create
### What issues does this PR fix or reference?
@W-11903179@ GH issue

2022-10-17 20:48 UTC, shetzel requested changes
Looks to me like we can remove a bunch of code in package beta version create command and rely on the library.

2022-10-17 20:48 UTC, shetzel commented on package.json
> +    "typescript-optional": "^2.0.1"
I see this as a dependency burden for syntactic sugar.

2022-10-17 20:48 UTC, shetzel commented on src/commands/force/package/beta/version/create.ts
> +  private resolvePackageIdFromFlags(): string {
`PackageVersion.create()` handles all of this already right? That's what I see when looking at library code for `packageVersionCreate.packageVersionCreate()`.

2022-10-17 21:06 UTC, peternhale commented on package.json
> +    "typescript-optional": "^2.0.1"
I will disagree.

2022-10-18 12:02 UTC, peternhale commented on package.json
> +    "typescript-optional": "^2.0.1"
Will remove

2022-10-18 21:33 UTC, shetzel approved these changes

2022-10-19 15:22 UTC, WillieRuemmele approved these changes

2022-10-24 12:06 UTC, merged