Wr/sf style
salesforcecli/plugin-packaging pull request #198
Opened 2022-12-28 23:43 UTC by WillieRuemmele

### What does this PR do?
make `plugin-packaging` friendly for `sf` and backwards compatible for `sfdx`

just pushing so I can see a diff

### What issues does this PR fix or reference?
@W-12083491@

2022-12-29 13:46 UTC, peternhale requested changes
@WillieRuemmele we have been removing `force` from the file structure to get rid of the `force` topic and then adding a command alias back to the original command.

I have also been trying to add the schema validation during this transition, since it is supported with SfProject.

2022-12-29 13:46 UTC, peternhale commented on src/commands/force/package/beta/convert.ts
>      Lifecycle.getInstance().on(PackageEvents.convert.progress, async (data: PackageVersionCreateEventData) => {
Maybe improve the user experience by replacing the scrolling progress with a spinner?

2022-12-29 13:46 UTC, peternhale commented on src/commands/force/package/beta/install.ts
> +    command: Install | Report,
Can we find a way around passing an instance of the command just to get access to the log method? I see this as the same pattern we using in core; emit a lifecycle event that the command is listening for.

2022-12-29 13:46 UTC, peternhale commented on src/commands/force/package/beta/installed/list.ts
> +    // @ts-ignore
@WillieRuemmele why the need for a ts-ignore?

2022-12-29 13:46 UTC, peternhale commented on src/commands/force/package/beta/version/create.ts
> -        ...this.flags,
``` suggestion
...Object.fromEntries(Object.entries(flags).map(([key, value]) => [key.replace(/-/g, ''), value]));
```

2022-12-29 13:46 UTC, peternhale commented on src/commands/force/package/beta/version/promote.ts
> +      if (!(await this.confirm(messages.getMessage('packageVersionPromoteConfirm', [flags.package])))) {
I would suggest throwing an error here instead having to ts-ignore the empty return with a message like `User abandoned promote`

2023-01-06 15:38 UTC, peternhale requested changes

2023-01-06 15:38 UTC, peternhale commented on src/commands/package/version/displayancestry.ts
> +export type DisplayAncestryCommandResult = PackageAncestryNodeData | string;
``` suggestion
export type DisplayAncestryCommandResult = PackageAncestryNodeData | string | void;
```

2023-01-06 15:38 UTC, peternhale commented on src/commands/package/version/displayancestry.ts
> +    return jsonProducer.produce() as PackageAncestryNodeData;
remove cast

2023-01-06 15:38 UTC, peternhale commented on src/commands/package/version/list.ts
>          const AliasStr = aliases.length > 0 ? aliases.join() : '';
I know this has been this was for a while, but not sure this correct.
The code above finds and retains a list of aliases for a package id.

AliasStr is the join of these aliases with no delimiter, so aliases ['a','b','c'] becomes `abc` which makes no sense.

2023-01-06 15:38 UTC, peternhale commented on src/commands/package/version/list.ts
>          });
``` suggestion
        const aliases: string[] = ids.map((id) => project.getAliasesFromPackageId(id)).flat();
```

2023-01-06 15:38 UTC, peternhale commented on src/commands/package/version/promote.ts
> +    return result;
``` suggestion
    try {
      const result = await packageVersion.promote();
      result.id = packageVersionData.SubscriberPackageVersionId;
      this.log(messages.getMessage('humanSuccess', [result.id]));
      return result;
    } catch (e) {
      const err = SfError.wrap(e as Error);
      if (err.name === 'DUPLICATE_VALUE' && err.message.includes('previously released')) {
        err.message = messages.getMessage('previouslyReleasedMessage');
        err.actions = [messages.getMessage('previouslyReleasedAction')];
      }
      throw err;
    }
```

2023-01-06 15:38 UTC, peternhale commented on src/commands/package/version/update.ts
> +  public static readonly aliases = ['force:package:beta:version:update', 'force:package:version:update'];
@WillieRuemmele why are the `beta` command aliases being retained to allow customer some time to adjust CI/CD?

2023-01-06 15:38 UTC, peternhale commented on src/commands/package/version/update.ts
> +    this.log(messages.getMessage('success', [result.id]));
this.logSuccess

2023-01-06 20:28 UTC, WillieRuemmele commented on src/commands/package/version/update.ts
> +  public static readonly aliases = ['force:package:beta:version:update', 'force:package:version:update'];
they were left as part of the packaging GA

2023-01-06 21:22 UTC, peternhale approved these changes

2023-01-25 17:45 UTC, merged