fix: add pkg create and delete commands
salesforcecli/plugin-packaging pull request #28
Opened 2022-07-13 21:08 UTC by peternhale

### What does this PR do?
add pkg create and delete commands
### What issues does this PR fix or reference?
@W-0@

2022-07-13 21:24 UTC, WillieRuemmele approved these changes

2022-07-13 21:24 UTC, WillieRuemmele commented on src/commands/force/package/beta/create.ts
> +      // TODO: until package2 is GA, wrap perm-based errors w/ 'contact sfdc' action (REMOVE once package2 is GA'd)
is this comment still accurate? - same in delete

2022-07-13 21:24 UTC, WillieRuemmele commented on src/commands/force/package/beta/create.ts
> +      this.hubOrg.getConnection(),
can we simplify the `createPackage` args so that you only pass `this.hubOrg` and get the connection from it in the method?

2022-08-01 15:28 UTC, peternhale commented on src/commands/force/package/beta/create.ts
> +      // TODO: until package2 is GA, wrap perm-based errors w/ 'contact sfdc' action (REMOVE once package2 is GA'd)
Yes

2022-08-01 15:38 UTC, WillieRuemmele requested changes
can we add tests?

2022-08-01 16:17 UTC, peternhale commented on src/commands/force/package/beta/create.ts
> +      this.hubOrg.getConnection(),
@WillieRuemmele I am trying to create APIs that require the minimum amount of data. I struggled a bit with passing just the connection or an org. I landed on connection, since the actual call only requires a connection.

2022-08-01 16:19 UTC, peternhale commented
> 

I was hoping to tackle this once we met critical mass. For these commands we have mostly flags (black box), calling the api and table output (more black box).

2022-08-11 21:33 UTC, shetzel requested changes
Switching from `this.prompt` to use `this.ux.confirm` is my requested change.
1 NUT per command would be good before the work item is closed.  Eventually there should be unit tests as well.
I would look at the yarn.lock file too.  Looks like there are a bunch of differences where the version is downgraded.  Might have to regenerate it.

2022-08-11 21:33 UTC, shetzel commented on src/commands/force/package/beta/create.ts
> +    const result: { Id: string } = await createPackage(this.hubOrg.getConnection(), this.project, options).catch(
At some point we need to decide how the plugin commands should call the packaging lib (consistency).  Maybe calling the function implementations directly is the way to go (like you have here) or maybe we could work with the `Package` class like this: `new Package({ connection }).create(options);` or maybe as a static function like this: `Package.create(connection, options)`.  I like the simplicity of only requiring the `Package` class and having the main functions available on it, rather than trying to figure out (as a consumer of the library) the individual functions I need.  Of course, developer tools help with that part because it should provide the exported functions, but that could be a long scrolling list too.  If the main functions are on the Package class consumers could do things like:
```typescript
const pkg = new Package({ connection });
const myPkg = await pkg.create(createOptions);
await pkg.waitForPublish(myPkg.Id);
await pkg.install(installOptions);
```

2022-08-11 21:33 UTC, shetzel commented on src/commands/force/package/beta/create.ts
> +        throw applyErrorAction(err);
why doesn't the library throw a better error so the command doesn't have to do this?

2022-08-11 21:33 UTC, shetzel commented on src/commands/force/package/beta/delete.ts
> +    const accepted = await this.prompt(
Using `this.ux.confirm` does most of this for us so `this.prompt` is not necessary.

2022-08-15 12:23 UTC, peternhale commented on src/commands/force/package/beta/create.ts
> +    const result: { Id: string } = await createPackage(this.hubOrg.getConnection(), this.project, options).catch(
@shetzel I agree. I also like a "classic" Package class approach that gives one a "one-stop-shopping" experience. I would like to get together and discuss this once we are past the critical command impls.

2022-08-15 12:26 UTC, peternhale commented on src/commands/force/package/beta/create.ts
> +    if (!this.flags.json) {
I will check, crossing sf vs sfdx command classes.

Regarding tests, the nuts for these exist in packaging library, where they belong, IMO.

2022-08-18 19:45 UTC, shetzel approved these changes

2022-08-18 21:53 UTC, merged