fix: strict null checks
salesforcecli/plugin-packaging pull request #322
Opened 2023-05-01 16:00 UTC by peternhale

### What does this PR do?
Applies TS strict null check rules
### What issues does this PR fix or reference?
@W-12220467@

This PR introduces changes to the json schema for commands 
`src/commands/package/version/displayancestry.ts`
`src/commands/package/version/report.ts`

2023-05-01 17:40 UTC, WillieRuemmele requested changes

2023-05-01 17:40 UTC, WillieRuemmele commented on src/commands/package/version/report.ts
> +type Omission = (typeof omissions)[number];
cool way refactor that type

2023-05-01 17:40 UTC, WillieRuemmele commented on src/commands/package/version/report.ts
> +    console.error('results - keys', Object.keys(results));
will need to remove this

2023-05-01 17:40 UTC, WillieRuemmele commented on src/commands/package/version/report.ts
> +    record.ConvertedFromVersionId = results.ConvertedFromVersionId ?? ' ';
strictNull doesn't like `??=`?

2023-05-01 17:40 UTC, WillieRuemmele commented on test/commands/package/install.test.ts
> +      expect(uxWarnStub.firstCall.args[0]).to.include(
it's been suggested to me to make this `uxWarnStub.firstCall.find(x => x.includes('The "-u"...'))` to avoid such rigid UTs around ux warnings

2023-05-02 12:13 UTC, peternhale commented on src/commands/package/version/report.ts
> +    record.ConvertedFromVersionId = results.ConvertedFromVersionId ?? ' ';
will look

2023-05-02 12:25 UTC, peternhale commented on test/commands/package/install.test.ts
> +      expect(uxWarnStub.firstCall.args[0]).to.include(
Generally speaking, using find erases order and order might be the desired test. I'd rather "fight with the index" to maintain the integrity the test. Uts are supposed to be fragile, as they detect unintended changes.

2023-05-02 13:50 UTC, WillieRuemmele approved these changes

2023-05-02 16:12 UTC, merged