Download package version
salesforcecli/plugin-packaging pull request #346
Opened 2023-05-30 14:39 UTC by andrewslater

### What does this PR do?
Adds a new command `package:version:retrieve` which retrieves metadata for a previously published package version.

### What issues does this PR fix or reference?
@W-12557202@

2023-05-30 16:41 UTC, ganeshnt commented on messages/package_version_retrieve.md
> +# summary
@andrewslater how about describing the applicable limits in here?

2023-05-30 16:41 UTC, ganeshnt commented on src/commands/package/version/retrieve.ts
> +  public static readonly hidden = true;
"true" until core side changes from 246 roll out?

2023-05-30 16:41 UTC, ganeshnt commented on src/commands/package/version/retrieve.ts
> +    const result: PackageVersionMetadataDownloadResult = await Package.downloadPackageVersionMetadata(
i don't see a -w option, so this is a blocking call? if yes, what if when a large package or network latency times out the socket?

2023-05-30 16:41 UTC, ganeshnt commented on yarn.lock
do we have to check-in this file? i suppose this is IDE modified (and not hand edited) ?

2023-05-30 16:42 UTC, andrewslater commented on src/commands/package/version/retrieve.ts
> +  public static readonly hidden = true;
Correct. I'm going to create a WI to track the un-hiding of this command as we start to roll out 246

2023-05-30 16:44 UTC, andrewslater commented on src/commands/package/version/retrieve.ts
> +    const result: PackageVersionMetadataDownloadResult = await Package.downloadPackageVersionMetadata(
In my experience `-w` is only used for asynchronous (polling) operations. This command is comprised of a few synchronous calls so there is no need for `-w`. If the network call times out (or otherwise encounters an error) an error message (generic message + specific message from underlying library code) will be displayed to the user.

2023-05-30 16:46 UTC, andrewslater commented on messages/package_version_retrieve.md
> +# summary
I'll run this by Penelope.

2023-05-30 16:54 UTC, ganeshnt commented on src/commands/package/version/retrieve.ts
> +    const result: PackageVersionMetadataDownloadResult = await Package.downloadPackageVersionMetadata(
that means if the command times out, then there wont be any files in the target folder.  user has to retry.  this should be considered when implementing the limits such that we count only successful completion.  it could be tricky/hard.  something worth discussion on limits user story

2023-05-30 16:55 UTC, ganeshnt approved these changes

2023-05-31 18:38 UTC, shetzel requested changes

2023-05-31 18:38 UTC, shetzel commented on messages/package_version_retrieve.md
> +Subscriber package version ID (starts with 04t).
Do you also want to support 04t aliases defined in `sfdx-project.json`?  Looks like the library doesn't support it so you'd have to add it, but just in case you did (because lots of other packaging commands do) this message would need updating.

2023-06-07 13:43 UTC, andrewslater commented on messages/package_version_retrieve.md
> +Subscriber package version ID (starts with 04t).
I have another change I'll need to make to the packaging library. I'll add alias support when I do that.

2023-06-07 13:43 UTC, andrewslater commented on src/commands/package/version/retrieve.ts
> +      summary: messages.getMessage('flags.package.summary'),
Marked as required.

2023-06-07 13:44 UTC, andrewslater commented on src/commands/package/version/retrieve.ts
> +      summary: messages.getMessage('flags.outputDir.summary'),
Specified default value.

2023-06-07 13:47 UTC, andrewslater commented on src/commands/package/version/retrieve.ts
> +    const result: PackageVersionMetadataDownloadResult = await Package.downloadPackageVersionMetadata(
Since this command is comprised of two http requests and some file manipulations on the returned data I don't plan to add a `-w` option. I don't think we typically add retries for http requests made during command execution so I don't plan on adding it. If the request times out or fails for some intermittent reason the user can easily re-run the command.

2023-06-07 13:48 UTC, andrewslater commented on src/commands/package/version/retrieve.ts
> +      }
Great catch. I updated this logic and the associated test.

2023-06-07 13:48 UTC, andrewslater commented on test/commands/package/packageVersionRetrieve.test.ts
> +    }),
Done.

2023-06-07 16:01 UTC, shetzel approved these changes

2023-06-07 20:06 UTC, merged