Wr/package version create
salesforcecli/plugin-packaging pull request #45
Opened 2022-08-18 15:22 UTC by WillieRuemmele

### What does this PR do?
adds `package:beta:version:create`
move more stuff into the library, resolve package alias/ids in the plugin

### What issues does this PR fix or reference?
@W-11444194@
requires: https://github.com/forcedotcom/packaging/pull/18

2022-08-18 17:55 UTC, peternhale requested changes

2022-08-18 17:55 UTC, peternhale commented on src/commands/force/package/beta/version/create.ts
> +import { PackageVersionCreateRequestResult } from '../../../../../../../packaging/src/interfaces';
@WillieRuemmele this import does not seem correct.

2022-08-18 17:55 UTC, peternhale commented on src/commands/force/package/beta/version/create.ts
> +      const status = data as unknown as PackageVersionCreateRequestResult & { remainingWaitTime: Duration };
data's type is `PackageVersionCreateEventData`

2022-08-18 20:21 UTC, peternhale approved these changes

2022-08-19 22:03 UTC, shetzel approved these changes

2022-08-20 00:01 UTC, merged