Wr/package convert
salesforcecli/plugin-packaging pull request #66
Opened 2022-09-01 20:08 UTC by WillieRuemmele

### What does this PR do?
adds `package:convert` command
adds UTs
no NUTs due to org restrictions

### NOTICE
I never was able to successfully test this command. I was able to reproduce the same errors as toolbelt, but couldn't verify the successful path (this would be great if packaging could help here)

### What issues does this PR fix or reference?
@W-10832894@
requires: https://github.com/forcedotcom/packaging/pull/31

2022-09-01 20:15 UTC, peternhale requested changes

2022-09-01 20:15 UTC, peternhale commented on src/commands/force/package/beta/convert.ts
> +      SfProject.getInstance()
Seems like this command needs to be in a project dir. Is that correct?

2022-09-01 20:15 UTC, peternhale commented on src/commands/force/package/beta/convert.ts
> +    switch (result.Status) {
This should be in library

2022-09-01 20:26 UTC, WillieRuemmele commented on src/commands/force/package/beta/convert.ts
> +      SfProject.getInstance()
I went back and forth, it's not required in TB. If it's in a project, it'll save to the project json, otherwise it won't - so it's optional

2022-09-01 20:29 UTC, WillieRuemmele commented on src/commands/force/package/beta/convert.ts
> +    switch (result.Status) {
we can add this to the refactoring list too then https://github.com/salesforcecli/plugin-packaging/blob/main/src/commands/force/package/beta/version/create.ts#L198

2022-09-07 16:57 UTC, peternhale commented on src/commands/force/package/beta/convert.ts
> +      SfProject.getInstance()
@WillieRuemmele can you check with packaging team to verify that a project is optional. Command not working when not in a project seems like an indication that a project is required.

2022-09-09 20:42 UTC, peternhale approved these changes

2022-09-09 20:42 UTC, merged