feat: async validation for package version create
salesforcecli/plugin-packaging pull request #687
Opened 2024-06-11 22:43 UTC by mradulsf

### What does this PR do?

### What issues does this PR fix or reference?

2024-06-14 23:08 UTC, shetzel requested changes
We rely heavily on tests and specifically NUTs to ensure correct packaging command behavior.  Please add some so we know it's working properly and can catch regressions.

2024-06-14 23:08 UTC, shetzel commented on src/commands/package/version/create.ts
> +      aliases: ['asyncvalidation'],
We don't want `asyncvalidation` as an alias.  The reason all the other flags have aliases is because we migrated this plugin from the "sfdx CLI" style to the new "sf CLI" style.
You can remove `deprecateAliases: true` and `aliases: ['asyncvalidation']`

2024-06-14 23:08 UTC, shetzel commented on src/commands/package/version/create.ts
> +        this.log(
nit: spacing looks off here

2024-06-17 15:39 UTC, mradulsf commented on src/commands/package/version/create.ts
> +      aliases: ['asyncvalidation'],
sure, let me make these changes

2024-06-18 16:36 UTC, shetzel approved these changes

2024-06-18 22:02 UTC, merged