feat: create/consume branch flag to filter PVL
salesforcecli/plugin-packaging pull request #690
Opened 2024-06-14 19:19 UTC by WillieRuemmele

### What does this PR do?
adds a `--branch` filter to `package version list` command

will only list packages on the specified branch

### What issues does this PR fix or reference?
@W-11167396@
REQUIRES: https://github.com/forcedotcom/packaging/pull/594

2024-06-14 21:51 UTC, jshackell-sfdc commented on messages/package_version_list.md
> +Use to filter the results to a specific branch
```suggestion
Branch in your source control system used to filter the results; only package versions based on the specified branch are listed. 
```

2024-06-14 21:52 UTC, jshackell-sfdc commented on messages/package_version_list.md
> +Use to filter the results to a specific branch
@WillieRuemmele , this is a bit wordy, I know.  But stylistically I can't start the description with a verb, I need to start with a description of the flag's value.  Let me know what you think, I can try again if you don't like it.

2024-06-14 21:56 UTC, jshackell-sfdc commented on messages/package_version_list.md
> +Use to filter the results to a specific branch
@WillieRuemmele , how about adding this new flag to an example, maybe the fourth one?  So it would be:

- List package versions that are based on the "featureA" branch in your source control system that were modified today in your default Dev Hub org; show limited details about each one:

2024-06-14 21:59 UTC, jshackell-sfdc requested changes
see my suggestions

2024-06-17 17:42 UTC, shetzel approved these changes

2024-06-17 19:05 UTC, jshackell-sfdc approved these changes

2024-06-18 22:58 UTC, merged