@W-15398724@ fix: remove codeCoverage field from non-verbose query for package ver…
salesforcecli/plugin-packaging pull request #723
Opened 2024-07-08 23:06 UTC by mradulsf

…sion list

### What does this PR do?

### What issues does this PR fix or reference?

2024-07-10 19:27 UTC, WillieRuemmele approved these changes

2024-07-11 16:54 UTC, t7job requested changes
The change looks good.  Can you add/update a test around this?

2024-07-11 17:52 UTC, WillieRuemmele commented on test/commands/package/packageVersion.nut.ts
> +      expect(codeCoverage).to.equal('use --verbose for code coverage');
```suggestion
      expect(output[0].CodeCoverage).to.equal...
```

this should already be a `string` (no .toString() required)
what's the `ts-ignore` ignoring?

2024-07-11 17:55 UTC, mradulsf commented on test/commands/package/packageVersion.nut.ts
> +      expect(codeCoverage).to.equal('use --verbose for code coverage');
ts-ignore i was using locally to test something, removed both.

2024-07-11 17:59 UTC, WillieRuemmele approved these changes

2024-07-11 17:59 UTC, WillieRuemmele commented on test/commands/package/packageVersion.nut.ts
> +        ?.result as PackageVersionListCommandResult;
NIT: shouldn't need to use `as` since you've cast it with `<PackageVersionListCommandResult>`

2024-07-11 17:59 UTC, WillieRuemmele commented on test/commands/package/packageVersion.nut.ts
> +      const codeCoverage = output?.[0]?.CodeCoverage || '';
NIT: no need to `|| ''` undefined is valid and will still fail the test

2024-07-11 18:10 UTC, mradulsf commented on test/commands/package/packageVersion.nut.ts
> +        ?.result as PackageVersionListCommandResult;
umm weird, it was throwing error without it earlier now its not. Fixed it!

2024-07-11 18:39 UTC, t7job approved these changes

2024-07-11 18:48 UTC, mradulsf commented
@WillieRuemmele I guess, it is okay to merge it?

2024-07-11 19:13 UTC, WillieRuemmele approved these changes

2024-07-11 19:14 UTC, WillieRuemmele commented
### QA Notes
---
✅ : `     "CodeCoverage": "use --verbose for code coverage",` in `--json` output
✅ : with `--verbose` -> `      "CodeCoverage": "100%",`, or `      "CodeCoverage": "",`

2024-07-11 19:15 UTC, merged