refactor: share common pkg install code
salesforcecli/plugin-packaging pull request #88
Opened 2022-09-15 21:31 UTC by shetzel

### What does this PR do?
Shares common code between `package:install` and `package:install:report` using a static method on the install command.

### What issues does this PR fix or reference?
@W-11757564@

2022-09-15 21:35 UTC, WillieRuemmele approved these changes

2022-09-16 11:58 UTC, peternhale requested changes

2022-09-16 11:58 UTC, peternhale commented on src/commands/force/package/beta/install.ts
> +      let errorMessage = '<empty>';
@shetzel I feel this belongs in a library, at least the portion that is rolling up the errors. Packaging has function combineSaveErrors in utils that does something similar. Maybe this belongs in SfError.

2022-09-16 15:40 UTC, shetzel commented on src/commands/force/package/beta/install.ts
> +      let errorMessage = '<empty>';
I don't think SfError should try to handle specific kinds of errors.  I'd feel differently if most/all errors from SFDC APIs had a similar structure but they don't.  Or maybe it is consistent from the SObject API and that can be an error that extends SfError?

I'm a bit conflicted with this one.  `Package.install()` returns a `PackageInstallRequest` and that has a lot of data on it.  Maybe a library consumer wants that object returned and doesn't want the error thrown.  Or at least if we throw the error, the error includes that object as data on the error.  That's something an `SfSObjectError` could handle.  What do you think of a new `SfSObjectError` error in core for this?

2022-09-19 13:27 UTC, peternhale commented on src/commands/force/package/beta/install.ts
> +      let errorMessage = '<empty>';
@shetzel I think an error like SfObjectError might be best, but maybe later.

2022-09-20 13:38 UTC, merged